### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by keithwang5** [AgoraIO-Usecase/eEducation#151]
The login was working well yesterday but I just tried logging in and receive this error:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/KeithWang/.nvm/versions/node/v13.5.0/bin/node',
1 verbose cli   '/Users/KeithWang/.nvm/versions/node/v13.5.0/bin/npm',
1 verbose cli   'start',
1 verbose cli   'run-script',
1 verbose cli   'debug'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v13.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Agora-Edu-Web@5.4.0~prestart: Agora-Edu-Web@5.4.0
6 info lifecycle Agora-Edu-Web@5.4.0~start: Agora-Edu-Web@5.4.0
7 verbose lifecycle Agora-Edu-Web@5.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle Agora-Edu-Web@5.4.0~start: PATH: /Users/KeithWang/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/KeithWang/Desktop/web/node_modules/.bin:/Users/KeithWang/Desktop/anaconda/anaconda3/condabin:/Users/KeithWang/.nvm/versions/node/v13.5.0/bin:/Users/KeithWang/Desktop/karuna/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/KeithWang/google-cloud-sdk/bin:/Users/KeithWang/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin
9 verbose lifecycle Agora-Edu-Web@5.4.0~start: CWD: /Users/KeithWang/Desktop/web
10 silly lifecycle Agora-Edu-Web@5.4.0~start: Args: [ '-c', 'node --inspect ./bin/www "run-script" "debug"' ]
11 silly lifecycle Agora-Edu-Web@5.4.0~start: Returned: code: 1  signal: null
12 info lifecycle Agora-Edu-Web@5.4.0~start: Failed to exec start script
13 verbose stack Error: Agora-Edu-Web@5.4.0 start: `node --inspect ./bin/www "run-script" "debug"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/KeithWang/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:305:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/KeithWang/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:305:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid Agora-Edu-Web@5.4.0
15 verbose cwd /Users/KeithWang/Desktop/web
16 verbose Darwin 18.7.0
17 verbose argv "/Users/KeithWang/.nvm/versions/node/v13.5.0/bin/node" "/Users/KeithWang/.nvm/versions/node/v13.5.0/bin/npm" "start" "run-script" "debug"
18 verbose node v13.5.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error Agora-Edu-Web@5.4.0 start: `node --inspect ./bin/www "run-script" "debug"`
22 error Exit status 1
23 error Failed at the Agora-Edu-Web@5.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

What went wrong?

**Comment by Matrixbirds** [comment]
It seems the network environment caused. can u give me how to reproduce it?
