### ISSUE TITLE
登录crash

### ISSUE THREAD

**Issue by abneryan** [AgoraIO-Usecase/eEducation#46]
12-15 17:21:15.142 27780-27780/io.agora.education E/CrashReport: Java Crash Happen cause by main(1)
12-15 17:21:15.182 27780-27780/io.agora.education E/CrashReport: stack frame :1, has cause true
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: #++++++++++Record By Bugly++++++++++#
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # PKG NAME: io.agora.education
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # APP VER: 6.0.0
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # SDK VER: 3.3.1-3.7.5
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # LAUNCH TIME: 2020-12-15 17:21:05
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH TYPE: JAVA_CRASH
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH TIME: 2020-12-15 17:21:15
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH PROCESS: io.agora.education
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH THREAD: main
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # REPORT ID: 9cf94e8d-1516-494e-8fda-d9ce178f0d90
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH DEVICE: HUAWEI M2-801W UNROOT
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # RUNTIME AVAIL RAM:1340436480 ROM:12745621504 SD:12724649984
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # RUNTIME TOTAL RAM:2932654080 ROM:26522972160 SD:26502000640
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH STACK: 
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25)
        at io.agora.education.api.manager.EduManager.init(EduManager.kt)
        at io.agora.education.MainActivity.start(MainActivity.java:203)
        at io.agora.education.MainActivity.onClick(MainActivity.java:139)
        at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:4792)
        at android.view.View$PerformClick.run(View.java:19938)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: java.lang.IllegalArgumentException: cannot initialize Agora RTM Service, error: 3
        at io.agora.rtm.internal.RtmClientImpl.initRtmService(RtmClientImpl.java:141)
        at io.agora.rtm.internal.RtmClientImpl.<init>(RtmClientImpl.java:116)
        at io.agora.rtm.internal.RtmManager.createRtmInstance(RtmManager.java:20)
        at io.agora.rtm.RtmClient.createInstance(RtmClient.java:65)
        at io.agora.rte.RteEngineImpl.init(RteEngineImpl.kt:128)
        at io.agora.education.impl.manager.EduManagerImpl.<init>(EduManagerImpl.kt:71)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25) 
        at io.agora.education.api.manager.EduManager.init(EduManager.kt) 
        at io.agora.education.MainActivity.start(MainActivity.java:203) 
        at io.agora.education.MainActivity.onClick(MainActivity.java:139) 
        at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18) 
        at android.view.View.performClick(View.java:4792) 
        at android.view.View$PerformClick.run(View.java:19938) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5601) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
12-15 17:21:15.572 27780-27780/io.agora.education E/CrashReport: sys default last handle start!
12-15 17:21:15.572 27780-27780/io.agora.education E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.agora.education, PID: 27780
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25)
        at io.agora.education.api.manager.EduManager.init(EduManager.kt)
        at io.agora.education.MainActivity.start(MainActivity.java:203)
        at io.agora.education.MainActivity.onClick(MainActivity.java:139)
        at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:4792)
        at android.view.View$PerformClick.run(View.java:19938)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: java.lang.IllegalArgumentException: cannot initialize Agora RTM Service, error: 3
        at io.agora.rtm.internal.RtmClientImpl.initRtmService(RtmClientImpl.java:141)
        at io.agora.rtm.internal.RtmClientImpl.<init>(RtmClientImpl.java:116)
        at io.agora.rtm.internal.RtmManager.createRtmInstance(RtmManager.java:20)
        at io.agora.rtm.RtmClient.createInstance(RtmClient.java:65)
        at io.agora.rte.RteEngineImpl.init(RteEngineImpl.kt:128)
        at io.agora.education.impl.manager.EduManagerImpl.<init>(EduManagerImpl.kt:71)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25) 
        at io.agora.education.api.manager.EduManager.init(EduManager.kt) 
        at io.agora.education.MainActivity.start(MainActivity.java:203) 
        at io.agora.education.MainActivity.onClick(MainActivity.java:139) 
        at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18) 
        at android.view.View.performClick(View.java:4792) 
        at android.view.View$PerformClick.run(View.java:19938) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5601) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by Chen-Alexander** [comment]
> 12-15 17:21:15.142 27780-27780/io.agora.education E/CrashReport: Java Crash Happen cause by main(1)
> 12-15 17:21:15.182 27780-27780/io.agora.education E/CrashReport: stack frame :1, has cause true
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: #++++++++++Record By Bugly++++++++++#
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # You can use Bugly(http:\bugly.qq.com) to get more Crash Detail!
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # PKG NAME: io.agora.education
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # APP VER: 6.0.0
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # SDK VER: 3.3.1-3.7.5
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # LAUNCH TIME: 2020-12-15 17:21:05
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH TYPE: JAVA_CRASH
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH TIME: 2020-12-15 17:21:15
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH PROCESS: io.agora.education
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH THREAD: main
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # REPORT ID: 9cf94e8d-1516-494e-8fda-d9ce178f0d90
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH DEVICE: HUAWEI M2-801W UNROOT
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # RUNTIME AVAIL RAM:1340436480 ROM:12745621504 SD:12724649984
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # RUNTIME TOTAL RAM:2932654080 ROM:26522972160 SD:26502000640
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: # CRASH STACK:
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
> Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
> Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Constructor.newInstance(Native Method)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
> at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25)
> at io.agora.education.api.manager.EduManager.init(EduManager.kt)
> at io.agora.education.MainActivity.start(MainActivity.java:203)
> at io.agora.education.MainActivity.onClick(MainActivity.java:139)
> at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77)
> at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
> at android.view.View.performClick(View.java:4792)
> at android.view.View$PerformClick.run(View.java:19938)
> at android.os.Handler.handleCallback(Handler.java:739)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:135)
> at android.app.ActivityThread.main(ActivityThread.java:5601)
> at java.lang.reflect.Method.invoke(Native Method) 
> at java.lang.reflect.Method.invoke(Method.java:372) 
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
> Caused by: java.lang.IllegalArgumentException: cannot initialize Agora RTM Service, error: 3
> at io.agora.rtm.internal.RtmClientImpl.initRtmService(RtmClientImpl.java:141)
> at io.agora.rtm.internal.RtmClientImpl.(RtmClientImpl.java:116)
> at io.agora.rtm.internal.RtmManager.createRtmInstance(RtmManager.java:20)
> at io.agora.rtm.RtmClient.createInstance(RtmClient.java:65)
> at io.agora.rte.RteEngineImpl.init(RteEngineImpl.kt:128)
> at io.agora.education.impl.manager.EduManagerImpl.(EduManagerImpl.kt:71)
> at java.lang.reflect.Constructor.newInstance(Native Method) 
> at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
> at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25) 
> at io.agora.education.api.manager.EduManager.init(EduManager.kt) 
> at io.agora.education.MainActivity.start(MainActivity.java:203) 
> at io.agora.education.MainActivity.onClick(MainActivity.java:139) 
> at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77) 
> at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18) 
> at android.view.View.performClick(View.java:4792) 
> at android.view.View$PerformClick.run(View.java:19938) 
> at android.os.Handler.handleCallback(Handler.java:739) 
> at android.os.Handler.dispatchMessage(Handler.java:95) 
> at android.os.Looper.loop(Looper.java:135) 
> at android.app.ActivityThread.main(ActivityThread.java:5601) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at java.lang.reflect.Method.invoke(Method.java:372) 
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
> 12-15 17:21:15.192 27780-27780/io.agora.education E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
> 12-15 17:21:15.572 27780-27780/io.agora.education E/CrashReport: sys default last handle start!
> 12-15 17:21:15.572 27780-27780/io.agora.education E/AndroidRuntime: FATAL EXCEPTION: main
> Process: io.agora.education, PID: 27780
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
> Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
> Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Constructor.newInstance(Native Method)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
> at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25)
> at io.agora.education.api.manager.EduManager.init(EduManager.kt)
> at io.agora.education.MainActivity.start(MainActivity.java:203)
> at io.agora.education.MainActivity.onClick(MainActivity.java:139)
> at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77)
> at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
> at android.view.View.performClick(View.java:4792)
> at android.view.View$PerformClick.run(View.java:19938)
> at android.os.Handler.handleCallback(Handler.java:739)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:135)
> at android.app.ActivityThread.main(ActivityThread.java:5601)
> at java.lang.reflect.Method.invoke(Native Method) 
> at java.lang.reflect.Method.invoke(Method.java:372) 
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
> Caused by: java.lang.IllegalArgumentException: cannot initialize Agora RTM Service, error: 3
> at io.agora.rtm.internal.RtmClientImpl.initRtmService(RtmClientImpl.java:141)
> at io.agora.rtm.internal.RtmClientImpl.(RtmClientImpl.java:116)
> at io.agora.rtm.internal.RtmManager.createRtmInstance(RtmManager.java:20)
> at io.agora.rtm.RtmClient.createInstance(RtmClient.java:65)
> at io.agora.rte.RteEngineImpl.init(RteEngineImpl.kt:128)
> at io.agora.education.impl.manager.EduManagerImpl.(EduManagerImpl.kt:71)
> at java.lang.reflect.Constructor.newInstance(Native Method) 
> at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
> at io.agora.education.api.manager.EduManager$Companion.init(EduManager.kt:25) 
> at io.agora.education.api.manager.EduManager.init(EduManager.kt) 
> at io.agora.education.MainActivity.start(MainActivity.java:203) 
> at io.agora.education.MainActivity.onClick(MainActivity.java:139) 
> at io.agora.education.MainActivity_ViewBinding$4.doClick(MainActivity_ViewBinding.java:77) 
> at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18) 
> at android.view.View.performClick(View.java:4792) 
> at android.view.View$PerformClick.run(View.java:19938) 
> at android.os.Handler.handleCallback(Handler.java:739) 
> at android.os.Handler.dispatchMessage(Handler.java:95) 
> at android.os.Looper.loop(Looper.java:135) 
> at android.app.ActivityThread.main(ActivityThread.java:5601) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at java.lang.reflect.Method.invoke(Method.java:372) 
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

你好，请检查一下传入的appId是否正确（EduManagerOptions.appId）。
