### ISSUE TITLE
education-web - Join Board Room Problem

### ISSUE THREAD

**Issue by mohit67890** [AgoraIO-Usecase/eEducation#56]
Hi, 

I tried the education-web version and received the following error.

`[White] join room fail
console.<computed> @ index.js:1406
(anonymous) @ index.ts:105
n.<computed> @ eruda.js:18727
overrideMethod @ react_devtools_backend.js:2430
e.log @ index.js:21010
(anonymous) @ index.js:21026
(anonymous) @ index.js:38196
(anonymous) @ index.js:37586
(anonymous) @ index.js:37598
s @ index.js:37495
Promise.then (async)
c @ index.js:37505
(anonymous) @ index.js:37508
a @ index.js:37484
t.connect @ index.js:38161
(anonymous) @ index.js:19945
(anonymous) @ index.js:19838
(anonymous) @ index.js:19850
(anonymous) @ index.js:19760
i @ index.js:19736
e.joinRoom @ index.js:19913
join @ board-client.ts:49
join @ board.ts:343
executeAction @ mobx.module.js:1061
join @ mobx.module.js:1041
init @ board.ts:223
async function (async)
init @ board.ts:222
executeAction @ mobx.module.js:1061
init @ mobx.module.js:1041
join @ room.ts:1200
async function (async)
join @ room.ts:820
executeAction @ mobx.module.js:1061
join @ mobx.module.js:1041
(anonymous) @ index.tsx:73
commitHookEffectListMount @ react-dom.development.js:19607
commitPassiveHookEffects @ react-dom.development.js:19644
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
flushPassiveEffectsImpl @ react-dom.development.js:22708
unstable_runWithPriority @ scheduler.development.js:656
runWithPriority$1 @ react-dom.development.js:11076
flushPassiveEffects @ react-dom.development.js:22676
performSyncWorkOnRoot @ react-dom.development.js:21591
(anonymous) @ react-dom.development.js:11130
unstable_runWithPriority @ scheduler.development.js:656
runWithPriority$1 @ react-dom.development.js:11076
flushSyncCallbackQueueImpl @ react-dom.development.js:11125
flushSyncCallbackQueue @ react-dom.development.js:11113
unbatchedUpdates @ react-dom.development.js:21766
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24573
render @ react-dom.development.js:24656
./src/index.tsx @ index.tsx:27
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
0 @ main.chunk.js:30267
__webpack_require__ @ bootstrap:785
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1406 [White] Error: invalid room token: undefined
    at Object.t.getAccessWithToken (http://localhost:3000/static/js/0.chunk.js:450252:15)
    at e.<anonymous> (http://localhost:3000/static/js/0.chunk.js:449416:29)
    at http://localhost:3000/static/js/0.chunk.js:449245:21
    at Object.next (http://localhost:3000/static/js/0.chunk.js:449257:12)
    at http://localhost:3000/static/js/0.chunk.js:449167:37
    at new Promise (<anonymous>)
    at n (http://localhost:3000/static/js/0.chunk.js:449143:14)
    at e.connect (http://localhost:3000/static/js/0.chunk.js:449401:16)
    at t.<anonymous> (http://localhost:3000/static/js/0.chunk.js:484542:87)
    at http://localhost:3000/static/js/0.chunk.js:483947:19
    at Object.next (http://localhost:3000/static/js/0.chunk.js:483959:10)
    at http://localhost:3000/static/js/0.chunk.js:483869:35
    at new Promise (<anonymous>)
    at a (http://localhost:3000/static/js/0.chunk.js:483845:12)
    at t.connect (http://localhost:3000/static/js/0.chunk.js:484522:14)
    at e.<anonymous> (http://localhost:3000/static/js/0.chunk.js:466306:19)
    at http://localhost:3000/static/js/0.chunk.js:466199:19
    at Object.next (http://localhost:3000/static/js/0.chunk.js:466211:10)
    at http://localhost:3000/static/js/0.chunk.js:466121:35
    at new Promise (<anonymous>)
    at i (http://localhost:3000/static/js/0.chunk.js:466097:12)
    at e.joinRoom (http://localhost:3000/static/js/0.chunk.js:466274:14)
    at BoardClient.join (http://localhost:3000/static/js/main.chunk.js:3647:35)
    at BoardStore.join (http://localhost:3000/static/js/main.chunk.js:21734:28)
    at executeAction (http://localhost:3000/static/js/0.chunk.js:298857:15)
    at BoardStore.join (http://localhost:3000/static/js/0.chunk.js:298837:12)
    at BoardStore.init (http://localhost:3000/static/js/main.chunk.js:21607:16)
    at async RoomStore.join (http://localhost:3000/static/js/main.chunk.js:28607:7)`

**Comment by srs888001** [comment]
It seems that the whiteboard token setting failed. Please check the whiteboard configuration.
