### ISSUE TITLE
index.js:7 RTM:ERROR RtmInvalidStatusError: Error Code 8. The SDK is either logging in or has logged in the Agora RTM system.

### ISSUE THREAD

**Issue by cwg31825** [AgoraIO-Usecase/eEducation#66]
index.js:7 RTM:ERROR RtmInvalidStatusError: Error Code 8. The SDK is either logging in or has logged in the Agora RTM system.
------------------
报这个问题 怎么解决？？

**Comment by cwg31825** [comment]
第一次老师进入房间没问题，关了客户端再进就报这个错误，提示老师已经存在

**Comment by plutoless** [comment]
麻烦提供一下完整的console日志

**Comment by cwg31825** [comment]
index.js:1 RTM:ERROR RtmInvalidStatusError: Error Code 8. The SDK is either logging in or has logged in the Agora RTM system.
    at t.<anonymous> (http://localhost:3000/static/js/1.chunk.js:88859:23)
    at l (http://localhost:3000/static/js/1.chunk.js:62377:20)
    at Generator._invoke (http://localhost:3000/static/js/1.chunk.js:62357:23)
    at Generator.e.(anonymous function) [as next] (http://localhost:3000/static/js/1.chunk.js:62414:25)
    at asyncGeneratorStep$9 (http://localhost:3000/static/js/1.chunk.js:86360:19)
    at s (http://localhost:3000/static/js/1.chunk.js:86377:11)
    at http://localhost:3000/static/js/1.chunk.js:86384:9
    at new Promise (<anonymous>)
    at t.<anonymous> (http://localhost:3000/static/js/1.chunk.js:86373:14)
    at t.<anonymous> (http://localhost:3000/static/js/1.chunk.js:89141:20)
    at t.<anonymous> (http://localhost:3000/static/js/1.chunk.js:88085:65)
    at l (http://localhost:3000/static/js/1.chunk.js:62377:20)
    at Generator._invoke (http://localhost:3000/static/js/1.chunk.js:62357:23)
    at Generator.e.(anonymous function) [as next] (http://localhost:3000/static/js/1.chunk.js:62414:25)
    at asyncGeneratorStep$9 (http://localhost:3000/static/js/1.chunk.js:86360:19)
    at s (http://localhost:3000/static/js/1.chunk.js:86377:11)
    at http://localhost:3000/static/js/1.chunk.js:86384:9
    at new Promise (<anonymous>)
    at t.<anonymous> (http://localhost:3000/static/js/1.chunk.js:86373:14)
    at t.<anonymous> (http://localhost:3000/static/js/1.chunk.js:88118:20)
    at t.n.value (http://localhost:3000/static/js/1.chunk.js:77376:17)
    at AgoraRTMClient.login (http://localhost:3000/static/js/main.chunk.js:12682:24)
    at RoomStore.loginAndJoin (http://localhost:3000/static/js/main.chunk.js:11043:26)
    at http://localhost:3000/static/js/main.chunk.js:9144:71
    at <anonymous> +9s

**Comment by cwg31825** [comment]
@ @plutoless

**Comment by cwg31825** [comment]
在房间发了消息后退出在进入会出现这个问题

**Comment by Matrixbirds** [comment]
这块可能是loginAndJoin这里引起的 rtm没有登出导致的，可以参考这个代码片段替换上您的demo里试试
```
  async loginAndJoin(payload: any, pass: boolean = false) {
    const {roomType, role, uid, rid, rtcToken, rtmToken} = payload;
    await this.rtmClient.login(uid, rtmToken);

    let result = {permitted: true, reason: ''};
    try {
      const channelMemberCount = await this.rtmClient.getChannelMemberCount([rid]);
      const channelCount = channelMemberCount[rid];
      let accounts = await this.rtmClient.getChannelAttributeBy(rid);
      const onlineStatus = await this.rtmClient.queryOnlineStatusBy(accounts);
      const argsJoin = {
        channelCount,
        onlineStatus,
        role,
        accounts,
        roomType
      };
      result = pass === false ? canJoin(argsJoin) : {permitted: true, reason: ''};
      if (result.permitted) {
        let res = await this.rtmClient.join(rid);
        this.state = {
          ...this.state,
          rtm: {
            ...this.state.rtm,
            joined: true
          },
          rtmToken,
          rtcToken,
        }
        const grantBoard = role === 'teacher' ? 1 : 0;
        await this.updateMe({...payload, grantBoard});
        this.commit(this.state);
        return;
      }
      throw {
        type: 'not_permitted',
        reason: result.reason
      }
    } catch (err) {
      if (this.rtmClient._logged) {
        await this.rtmClient.logout();
      }
      throw err;
    }
  }
```

**Comment by cwg31825** [comment]
Property '_logged' is private and only accessible within class 'AgoraRTMClient'.  TS2341

    615 |       }
    616 |     } catch (err) {
  > 617 |       if (this.rtmClient._logged) {
        |                          ^
    618 |         await this.rtmClient.logout();
    619 |       }
    620 |       throw err;

**Comment by Matrixbirds** [comment]
@cwg31825 
找到这里 src/utils/agora-rtm-client.ts
找到
```javascript
private _logged: boolan = false;
```
修改成
```javascript
public _logged: boolean = false;
```
