### ISSUE TITLE
提议：升级版本时请告知需要升级的文件和配置

### ISSUE THREAD

**Issue by seasun** [AgoraIO-Usecase/eEducation#9]
升级版本时请告知需要升级的文件和配置
如0.4.7升级到0.4.8，若只更新AgoraSDK是升级不成功的，需要替换掉app文件夹下的app.html

`module.js:545 Uncaught Error: Cannot find module './webgl-utils'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (E:\Node\Examples\LinkTeacher\ElectronLinkTeacher\node_modules\_electron@2.0.4@electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at file:///E:/Node/Examples/LinkTeacher/ElectronLinkTeacher/app/AgoraSDK/AgoraRender.js:1:34
AgoraSdk.js:1 Uncaught SyntaxError: Identifier 'EventEmitter' has already been declared
    at AgoraSdk.js:1`

**Comment by menthays** [comment]
很好的建议。不过有几个问题：
- 这个项目本身作为 sample code 最初在开发时许多细节（包括项目结构，业务逻辑实现，服务的设计）确实存在一些缺陷，目前的改动经常涉及到比较多的方面，某个依赖/工具链的config/前端业务逻辑/引用方式都有可能会发生变更，在这种情况下很难给出一个变更文件列表（因为几乎是全部，甚至不如直接看commit记录）。
- 我们有打算增加 CHANGELOG.md ，尽可能去描述一些变动和变动涉及到的点，再具体的内容可能就需要开发者自己关注了。
- 针对项目结构不稳定的问题，因为我们也仍在探索阶段，如果各位开发者对于结构上有什么疑问或是建议，或者能给出各位实际和希望的使用方式，那就再好不过了。
